---
title: "Proxy GxE MR results"
author: "Giulio Centorame"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    toc: 6
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(purrr)
library(ggplot2)
library(forcats)
library(tidyr)
library(broom)

show_table <- function(data){
  data %>%
    DT::datatable(filter = 'top', 
                options = list(pageLength = 5, autoWidth = TRUE)
  )
}

# Load env
base::load("../../temp/merged/model_summaries.RData")

```

```{r continuous-traits-forest-plot, echo = FALSE, fig.height=5, fig.width=7}

cognitive_measures <-
    c(
    "Verbal-numerical reasoning",
    "Matrix pattern completion",
    "Reaction time",
    "Tower rearranging",
    "Numeric memory",
    "Visual memory",
    "Paired associate learning",
    "Symbol digit substitution",
    "Trailmaking A",
    "Trailmaking B",
    "Trailmaking B-A"
    )

continuous_traits <- 
  c(
  "Body mass index",
  "LDL direct measurement",
  "HDL direct measurement",
  "Systolic blood pressure",
  "Diastolic blood pressure",
  "Years in full-time education",
  "Number of offspring"
)

binary_traits<- c(
    "Prospective memory",
    "Angina pectoris",
    "Myocardial infarction",
    "Stroke",
    "Hayfever, rhinitis, or eczema",
    "Diabetes"
)

summary_stats_plots %>%
  filter(outcome %in% continuous_traits) %>%
  ggplot(aes(x = outcome, y = estimate)) +
  geom_pointrange(aes(colour = stratum, 
                      group = variant, 
                     ymin = estimate - 1.96*std.error,
                     ymax = estimate + 1.96*std.error),
                    position = position_dodge2(width = 0.8),
                    fatten = 2
                     ) +
  facet_grid(variant ~ covariates) +
  theme_bw() +
    ggsci::scale_colour_npg()+
  labs(title = "SNP effect estimate by breastfeeding status",
       subtitle = "Error bars represent 95% confidence intervals",
       colour = "Breastfeeding status") +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        legend.position = "bottom",
        plot.margin = margin(10,10,10,50))+
  geom_hline(yintercept = 0, linetype = "dashed", colour = "darkgrey")
```

```{r cognitive-measures-forest-plot, echo=FALSE, fig.height=6, fig.width=10}
summary_stats_plots %>%
  filter(outcome %in% cognitive_measures) %>%
  ggplot(aes(x = outcome, y = estimate)) +
  geom_pointrange(aes(colour = stratum, 
                      group = variant, 
                     ymin = estimate - 1.96*std.error,
                     ymax = estimate + 1.96*std.error),
                    position = position_dodge2(width = 0.8),
                    fatten = 2
                     ) +
  facet_grid(variant ~ covariates) +
  theme_bw() +
  ggsci::scale_colour_npg()+
  labs(title = "SNP effect estimate by breastfeeding status",
       subtitle = "Error bars represent 95% confidence intervals",
       colour = "Breastfeeding status") +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        legend.position = "bottom",
        plot.margin = margin(10,10,10,50))+
  geom_hline(yintercept = 0, linetype = "dashed", colour = "darkgrey")
```

```{r binary-traits-forest-plot, echo = FALSE, fig.height=6, fig.width=10}
summary_stats_plots %>%
  filter(outcome %in% binary_traits) %>%
  ggplot(aes(x = outcome, y = estimate)) +
  geom_pointrange(aes(colour = stratum, 
                      group = variant, 
                     ymin = estimate - 1.96*std.error,
                     ymax = estimate + 1.96*std.error),
                    position = position_dodge2(width = 0.8),
                    fatten = 2
                     ) +
  facet_grid(variant ~ covariates) +
  theme_bw() +
    ggsci::scale_colour_npg()+
  labs(title = "SNP effect estimate by breastfeeding status",
       subtitle = "Error bars represent 95% confidence intervals",
       colour = "Breastfeeding status") +
  theme(axis.text.x = element_text(angle = 45, hjust=1),
        legend.position = "bottom",
        plot.margin = margin(10,10,10,50))+
  geom_hline(yintercept = 0, linetype = "dashed", colour = "darkgrey")
```

# Model summary printouts

## Coefficients

```{r model-coefficients, echo = FALSE}
summary_stats %>%
  relocate(outcome, covariates) %>%
  show_table()
```

```{r model-binary-traits, echo = FALSE}
model_summary_binary %>%
    relocate(outcome, covariates) %>%
  show_table()
```

```{r model-continuous-traits, echo = FALSE}
model_summary_continuous %>%
    relocate(outcome, covariates) %>%
  show_table()
```
